ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:toc: preamble
:toc-title: 목차
:toclevels: 2
:doctitle: 셀러리 API
:author: 터틀
:email: begaonnuri@gmail.com

Doc Writer <{author} : {email}>

[[resources-member]]
== 회원 관리

=== 회원 로그인

operation::login[snippets='http-request,http-response,request-fields,request-body']

=== 회원 로그인 실패

==== 이메일

operation::login/advice/email[snippets='http-request,http-response,request-fields,request-body,response-body']

==== 비밀번호

operation::login/advice/password[snippets='http-request,http-response,request-fields,request-body,response-body']

[[resources-articles]]
== 게시글 관리

=== 게시글 페이지 조회

operation::articles/getPage[snippets='http-request,http-response,request-parameters,response-body']

=== 게시글 상세 조회

operation::articles/get[snippets='http-request,http-response,path-parameters,request-parameters,response-body']

=== 게시글 생성

operation::articles/post[snippets='http-request,http-response,request-body,response-headers']

=== 게시글 수정

operation::articles/update[snippets='http-request,request-body']

== 채팅방 관리

=== 채팅방 생성

operation::chat-rooms/post[snippets='http-request,http-response,request-fields,request-body,response-headers']

== 조직 관리

=== 조직 생성

operation::organizations/create[snippets='http-request,request-headers,request-body,request-fields,http-response,response-body,response-fields']

=== 회원이 가입한 조직 조회

operation::organizations/get[snippets='http-request,request-headers,http-response,response-body,response-fields']

== 회원 / 조직 관리

=== 회원 - 조직 입장

operation::memberOrganization/create[snippets='http-request,request-headers,request-body,request-fields,http-response,response-headers']

